import os
import threading
import time
import logging

log = logging.getLogger('werkzeug')
log.setLevel(logging.ERROR)

from flask import Flask, render_template, request, jsonify, session
from flask_socketio import SocketIO, emit
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import base64
from gtts import gTTS

# Import our custom core components
from core.audio_io import AudioController
from core.brain import GarudaBrain
from core.database import VoiceLedger
from core import db_manager
from modules.agri_agent import AgricultureAgent
from modules.health_agent import HealthAgent
from modules.hunger_agent import ZeroHungerAgent

app = Flask(__name__)
app.config['SECRET_KEY'] = 'garuda_sanket_god_mode_2026'
socketio = SocketIO(app, cors_allowed_origins="*")

# Initialize global controllers
audio = AudioController()
audio.socketio = socketio
brain = GarudaBrain()
ledger = VoiceLedger()
db_manager.init_db()
agri = AgricultureAgent(ledger, brain)
health = HealthAgent(ledger, brain)
hunger = ZeroHungerAgent(ledger, brain)

# Keep track of current session state
session = {
    "language": "en",
    "city": None,
    "domain": None,
    "user_phone": "9876543210" # Default for demo; in production, capture from gateway
}

@app.route('/')
def index():
    return render_template('dashboard.html')

@app.route('/buyer')
def buyer():
    return render_template('buyer_dashboard.html')

@app.route('/panchayat')
def panchayat():
    return render_template('panchayat_dashboard.html')

@app.route('/donor')
def donor():
    return render_template('donor_dashboard.html')

@app.route('/admin_db')
def admin_db():
    data = db_manager.get_dashboard_data()
    return render_template('admin_db.html', data=data)

@app.route('/send_pdf_report', methods=['POST'])
def send_pdf_report():
    try:
        data = request.json
        pdf_base64 = data.get('pdf_data')
        
        if not pdf_base64:
            return jsonify({'status': 'error', 'msg': 'No PDF data provided'}), 400

        # Decode base64
        pdf_data = base64.b64decode(pdf_base64.split(',')[1])

        # Email details
        sender_email = "u6973364@gmail.com"
        sender_password = "iquraorjiuvhrqsj"
        receiver_email = "u6973364@gmail.com"

        # Construct email
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        msg['Subject'] = "Panchayat Analytics Report - Garuda Sanket"

        body = "Attached is the latest Panchayat Analytics Dashboard report generated by the Garuda Sanket system."
        msg.attach(MIMEText(body, 'plain'))

        # Attach PDF
        part = MIMEApplication(pdf_data, Name="Panchayat_Analytics_Report.pdf")
        part['Content-Disposition'] = 'attachment; filename="Panchayat_Analytics_Report.pdf"'
        msg.attach(part)

        # Send Email
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()

        return jsonify({'status': 'success', 'msg': 'Email sent successfully'})
    except Exception as e:
        print(f"Error sending email: {e}")
        return jsonify({'status': 'error', 'msg': str(e)}), 500

# --- SOCKET EVENTS: DASHBOARD CONTROLS ---

@socketio.on('trigger_start')
def handle_start():
    print("\n[ACTION] New Call Triggered via Dashboard")
    emit('status_update', {'msg': 'Call Started from Remote'}, broadcast=True)
    
    text = "Welcome to Vistara AI. Please select your language. Press 1 for English and 2 for Kannada."
    path = generate_ai_voice(text, "en")
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Vistara AI Intro)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('select_language')
def handle_language(data):
    session['language'] = data['lang']
    print(f"\n[ACTION] Language Selected: {session['language'].upper()}")
    emit('status_update', {'msg': f'Language set to {data["lang"].upper()}'}, broadcast=True)
    # Play confirmation/next menu (City Selection)
    if session['language'] == 'en':
        text = "Please select your city. Press 1 for Bangalore, 2 for Mysore, 3 for Mandya, 4 for Hassan."
    else:
        text = "ದಯವಿಟ್ಟು ನಿಮ್ಮ ನಗರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ. ಬೆಂಗಳೂರಿಗಾಗಿ 1, ಮೈಸೂರಿಗಾಗಿ 2, ಮಂಡ್ಯಕ್ಕಾಗಿ 3, ಹಾಸನಕ್ಕಾಗಿ 4 ಒತ್ತಿ."
        
    path = generate_ai_voice(text, session['language'])
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('select_city')
def handle_city(data):
    session['city'] = data['city']
    print(f"\n[ACTION] City Selected: {session['city'].upper()}")
    emit('status_update', {'msg': f'City set to {data["city"].upper()}'}, broadcast=True)
    
    # After city is selected, ask for Domain (Simplified for Zero Hunger)
    if session['language'] == 'en':
        text = "For food request press 1."
    else:
        text = "ಆಹಾರದ ವಿನಂತಿಗಾಗಿ 1 ಒತ್ತಿ."
        
    path = generate_ai_voice(text, session['language'])
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('ask_group_type')
def handle_ask_group_type():
    lang = session.get('language', 'en')
    text = "Are you an individual person or are you ordering for a group of people?" if lang == 'en' else "ನೀವು ಒಬ್ಬ ವ್ಯಕ್ತಿಯೇ ಅಥವಾ ಗುಂಪಿಗಾಗಿ ಆಹಾರವನ್ನು ಆದೇಶಿಸುತ್ತಿದ್ದೀರಾ?"
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    path = generate_ai_voice(text, lang)
    audio.play_voice(path)

@socketio.on('select_domain')
def handle_domain(data):
    session['domain'] = data['domain']
    print(f"\n[ACTION] Domain Selected: {session['domain'].upper()}")
    emit('status_update', {'msg': f'Domain Selected: {data["domain"].upper()}'}, broadcast=True)
    # Play specific sub-menu audio or welcome to the sector
    if session['domain'] == 'hunger':
        # Get group type and zone info
        group_type = data.get('group_type', 'individual')
        in_zone = data.get('in_zone', False)
        
        # Save in session
        session['in_zone'] = in_zone
        session['group_type'] = group_type
        
        # Skip options, immediately process a general food request
        lang = session.get('language', 'en')
        
        threading.Thread(target=audio.play_buffer).start()
        
        base_text = "Your food request has been sent to the donors. Please wait while we find a match." if lang == 'en' else "ನಿಮ್ಮ ಆಹಾರದ ವಿನಂತಿಯನ್ನು ದಾನಿಗಳಿಗೆ ಕಳುಹಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಕಾಯಿರಿ."
        
        # Store coordinates for later use in specific food type requests
        session['lat'] = data.get('lat')
        session['lng'] = data.get('lng')

        # Notify Donors - Use socketio.emit for global broadcast
        socketio.emit('new_food_request', {
            'phone': session['user_phone'],
            'city': session.get('city', 'Unknown'),
            'type': f'General Food ({group_type.title()})',
            'timestamp': time.strftime("%H:%M:%S"),
            'lat': session['lat'],
            'lng': session['lng'],
            'in_zone': in_zone
        })
        
        # --- BATCH SIMULATION LOGIC ---
        if group_type == 'individual':
            import random
            # Trigger Database Data Generation
            try:
                db_manager.generate_random_data()
                print("[DATABASE] Generated random data for User, Donor, Donation, and Transaction tables.")
            except Exception as e:
                print(f"[DATABASE ERROR] {e}")

            base_lat = session['lat'] or 12.9716
            base_lng = session['lng'] or 77.5946
            
            # Simulate 2 more in-zone users (close distance)
            for i in range(2):
                mock_lat = base_lat + random.uniform(-0.01, 0.01)
                mock_lng = base_lng + random.uniform(-0.01, 0.01)
                socketio.emit('new_food_request', {
                    'phone': f"9876543{random.randint(100,999)}",
                    'city': session.get('city', 'Unknown'),
                    'type': 'General Food (Individual)',
                    'timestamp': time.strftime("%H:%M:%S"),
                    'lat': mock_lat,
                    'lng': mock_lng,
                    'in_zone': True
                })
                
            # Simulate 2 out-zone users (far distance)
            for i in range(2):
                mock_lat = base_lat + random.uniform(0.04, 0.08)
                mock_lng = base_lng + random.uniform(0.04, 0.08)
                socketio.emit('new_food_request', {
                    'phone': f"9876543{random.randint(100,999)}",
                    'city': session.get('city', 'Unknown'),
                    'type': 'General Food (Individual)',
                    'timestamp': time.strftime("%H:%M:%S"),
                    'lat': mock_lat,
                    'lng': mock_lng,
                    'in_zone': False
                })
        
        base_text = "We have submitted your request to a nearby restaurant or hotel, please wait." if lang == 'en' else "ನಾವು ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಹತ್ತಿರದ ಹೋಟೆಲ್‌ಗೆ ಅಥವಾ ರೆಸ್ಟೋರೆಂಟ್‌ಗೆ ಸಲ್ಲಿಸಿದ್ದೇವೆ, ದಯವಿಟ್ಟು ಕಾಯಿರಿ."
        
        try:
            import ollama
            city = session.get('city', 'Unknown')
            language_instruction = "English" if lang == 'en' else "Kannada"
            prompt = f"Rewrite this comforting message: 'Your food request has been successfully sent to nearby donors and restaurants in {city}, please wait patiently as we search for a suitable match.' Write exactly 1 or 2 sentences. Reply in {language_instruction}."
            
            response = ollama.chat(model='tinyllama', messages=[
                {'role': 'system', 'content': 'You are a helpful assistant. Reply ONLY with the rewritten message. No conversational filler. No introductory phrases.'},
                {'role': 'user', 'content': prompt}
            ])
            text = response['message']['content']
            print(f"\n[TINYLLAMA REAL RESPONSE]\n{text}\n")
        except Exception as e:
            text = base_text
            try:
                print(f"\n[AI RESPONSE FALLBACK] {text}")
            except UnicodeEncodeError:
                print(f"\n[AI RESPONSE FALLBACK] (Kannada Text - Display Error in Console)")
                
        emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
        path = generate_ai_voice(text, lang)
        audio.play_voice(path)
        return # Exit early as we don't need further logic for this domain
        
    elif session['domain'] == 'agriculture':
        # (Currently deactivated as per user request)
        if session['language'] == 'en':
            text = "You selected Agriculture. Press 1 for Market Price, 2 for Pest Report, 3 for Sarkari Help."
        else:
            text = "ನೀವು ಕೃಷಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿದ್ದೀರಿ. ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಾಗಿ 1, ಕೀಟ ವರದಿಗಾಗಿ 2, ಸರ್ಕಾರಿ ಸಹಾಯಕ್ಕಾಗಿ 3 ಒತ್ತಿ."
    elif session['domain'] == 'health' or session['domain'] == 'healthcare':
        text = health.get_main_menu(session.get('language', 'en'))
    else:
        text = "Invalid domain."
            
    path = generate_ai_voice(text, session.get('language', 'en'))
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('health_action')
def handle_health_action(data):
    action = data['action']
    print(f"\n[ACTION] Health Action Triggered: {action.upper()}")
    emit('status_update', {'msg': f'Health Action: {action.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    if action == 'bp':
        text = health.get_bp_menu(lang)
    elif action == 'symptom':
        intro = health.get_symptom_intro(lang)
        menu = health.get_symptom_menu(lang)
        text = f"{intro} {menu}"
    elif action == 'sugar':
        text = health.get_sugar_menu(lang)
    elif action == 'medicine':
        # Placeholder for Medicine Reminder
        text = health.get_medicine_reminder(lang)
    else:
        text = "Invalid selection."
        
    path = generate_ai_voice(text, lang)
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('sugar_action')
def handle_sugar_action(data):
    level = data['level']
    print(f"\n[ACTION] Sugar Action Triggered: {level.upper()}")
    emit('status_update', {'msg': f'Sugar Range: {level.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    advice = health.get_sugar_advice(level, lang)
    safety = health.get_safety_message(lang)
    text = f"{advice} {safety}"
    
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    
    path = generate_ai_voice(text, lang)
    audio.stop_buffer()
    audio.play_voice(path)

@socketio.on('bp_action')
def handle_bp_action(data):
    level = data['level']
    print(f"\n[ACTION] BP Action Triggered: {level.upper()}")
    emit('status_update', {'msg': f'BP Range: {level.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    advice = health.get_bp_advice(level, lang)
    safety = health.get_safety_message(lang)
    text = f"{advice} {safety}"
    
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    
    path = generate_ai_voice(text, lang)
    audio.stop_buffer()
    audio.play_voice(path)

@socketio.on('symptom_action')
def handle_symptom_action(data):
    symptom = data['symptom']
    print(f"\n[ACTION] Symptom Triggered: {symptom.upper()}")
    emit('status_update', {'msg': f'Symptom: {symptom.replace("_", " ").upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    advice = health.get_symptom_advice(symptom, lang)
    safety = health.get_safety_message(lang)
    text = f"{advice} {safety}"
    
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    
    path = generate_ai_voice(text, lang)
    audio.stop_buffer()
    audio.play_voice(path)


@socketio.on('agri_action')
def handle_agri(data):
    action = data['action']
    print(f"\n[ACTION] Agri Action Triggered: {action.upper()}")
    emit('status_update', {'msg': f'Agri Action: {action.replace("_", " ").upper()}'}, broadcast=True)
    
    # 1. Start thinking sound
    threading.Thread(target=audio.play_buffer).start()
    
    # 2. Process logic based on action
    if action == 'market_price':
        response_text = agri.get_market_intelligence(session['user_phone'], session['language'])
    elif action == 'pest_report':
        response_text = agri.process_pest_report(session['user_phone'], session['language'])
    elif action == 'sarkari_help':
        response_text = agri.get_scheme_eligibility(session['user_phone'], session['language'])
    else:
        if session['language'] == 'en':
            response_text = "I am ready to help with your farming needs."
        else:
            response_text = "ನಿಮ್ಮ ಕೃಷಿ ಅಗತ್ಯಗಳಿಗೆ ಸಹಾಯ ಮಾಡಲು ನಾನು ಸಿದ್ಧನಿದ್ದೇನೆ."

    # 3. TTS Generation & Playback
    path = generate_ai_voice(response_text, session['language'])
    try:
        print(f"\n[AI RESPONSE] {response_text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {response_text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('market_response')
def handle_market_response(data):
    response = data['response']
    print(f"\n[ACTION] Market Response: {response.upper()}")
    emit('status_update', {'msg': f'Market Response: {response.upper()}'}, broadcast=True)
    
    if response == 'agree':
        text = "Great! We have recorded your interest in selling at this rate. Our agent will contact you soon." if session['language'] == 'en' else "ಉತ್ತಮ! ಈ ದರದಲ್ಲಿ ಮಾರಾಟ ಮಾಡಲು ನಿಮ್ಮ ಆಸಕ್ತಿಯನ್ನು ನಾವು ದಾಖಲಿಸಿದ್ದೇವೆ. ನಮ್ಮ ಏಜೆಂಟ್ ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ."
        
        import random
        price = random.randint(2000, 3500)
        emit('buyer_email_alert', {
            'phone': session.get('user_phone', '9876543210'),
            'city': session.get('city', 'Unknown').upper() if session.get('city') else 'Unknown',
            'price': price
        }, broadcast=True)
    else:
        text = "No problem. We will notify you when the prices change." if session['language'] == 'en' else "ತೊಂದರೆಯಿಲ್ಲ. ಬೆಲೆಗಳು ಬದಲಾದಾಗ ನಾವು ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ."
        
    path = generate_ai_voice(text, session['language'])
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('pest_action')
def handle_pest_action(data):
    problem = data['problem']
    print(f"\n[ACTION] Pest Problem Reported: {problem.upper()}")
    emit('status_update', {'msg': f'Pest Problem: {problem.replace("_", " ").upper()}'}, broadcast=True)
    
    solution_text = agri.get_pest_solution(problem, session['language'])
    
    path = generate_ai_voice(solution_text, session['language'])
    try:
        print(f"\n[AI RESPONSE] {solution_text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {solution_text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('sarkari_action')
def handle_sarkari_action(data):
    acreage = data['acreage']
    print(f"\n[ACTION] Acreage Selected: {acreage.upper()}")
    emit('status_update', {'msg': f'Acreage: {acreage.replace("_", " ").upper()}'}, broadcast=True)
    
    scheme_text = agri.get_scheme_details(acreage, session['language'])
    
    # --- NEW CODE FOR PANCHAYAT ANALYTICS ---
    scheme_name = "Kisan Samman Nidhi" if acreage == 'small' else "PM-KUSUM (Solar Pump)"
    emit('update_scheme_analytics', {'scheme': scheme_name}, broadcast=True)
    # ----------------------------------------
    
    path = generate_ai_voice(scheme_text, session['language'])
    try:
        print(f"\n[AI RESPONSE] {scheme_text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {scheme_text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('sarkari_final')
def handle_sarkari_final(data):
    decision = data['decision']
    print(f"\n[ACTION] Scheme Submission Decision: {decision.upper()}")
    emit('status_update', {'msg': f'Submission: {decision.upper()}'}, broadcast=True)
    
    if decision == 'agree':
        text = "Your application has been submitted successfully. Thank you!" if session['language'] == 'en' else "ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ. ಧನ್ಯವಾದಗಳು!"
    else:
        text = "Application cancelled. Let us know if you need help with anything else." if session['language'] == 'en' else "ಅರ್ಜಿಯನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ. ನಿಮಗೆ ಬೇರೆ ಯಾವುದಾದರೂ ಸಹಾಯ ಬೇಕಾದಲ್ಲಿ ನಮಗೆ ತಿಳಿಸಿ."
        
    path = generate_ai_voice(text, session['language'])
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    audio.play_voice(path)

@socketio.on('emergency_trigger')
def handle_emergency(data):
    level = data['level'] # RED, YELLOW, GREEN
    print(f"\n[EMERGENCY] {level} LEVEL ACTIVATED")
    emit('status_update', {'msg': f'🚨 EMERGENCY ACTIVATED: {level}'}, broadcast=True)
    
    # Immediately stop any other audio
    audio.stop_buffer()
    
    if level == 'RED':
        # 1. Start Priority logic
        instructions = health.get_triage_instructions("RED", session['language'])
        # 2. Trigger Hospital Email in Background
        threading.Thread(target=health.trigger_hospital_alert, args=(session['user_phone'],)).start()
        # 3. Speak instructions
        path = generate_ai_voice(instructions, session['language'])
        try:
            print(f"\n[AI RESPONSE] {instructions}")
        except UnicodeEncodeError:
            print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
        audio.play_voice(path)
    
    elif level == 'YELLOW':
        instructions = health.get_triage_instructions("YELLOW", session['language'])
        path = generate_ai_voice(instructions, session['language'])
        try:
            print(f"\n[AI RESPONSE] {instructions}")
        except UnicodeEncodeError:
            print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
        audio.play_voice(path)
        
    elif level == 'GREEN':
        instructions = health.get_triage_instructions("GREEN", session['language'])
        path = generate_ai_voice(instructions, session['language'])
        try:
            print(f"\n[AI RESPONSE] {instructions}")
        except UnicodeEncodeError:
            print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
        audio.play_voice(path)

# --- ZERO HUNGER EVENTS ---

@socketio.on('hunger_action')
def handle_hunger_action(data):
    action = data['action'] # 'request' or 'check'
    print(f"\n[ACTION] Hunger Action Triggered: {action.upper()}")
    emit('status_update', {'msg': f'Hunger Action: {action.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    if action == 'request':
        text = hunger.get_food_type_menu(lang)
    else:
        text = "You have no active food requests at the moment." if lang == 'en' else "ನಿಮಗೆ ಯಾವುದೇ ಸಕ್ರಿಯ ಆಹಾರ ವಿನಂತಿಗಳಿಲ್ಲ."
        
    path = generate_ai_voice(text, lang)
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('food_type_action')
def handle_food_type(data):
    food_type = data['type'] # 'grains', 'cooked', 'baby'
    print(f"\n[ACTION] Food Type Selected: {food_type.upper()}")
    emit('status_update', {'msg': f'Food Requested: {food_type.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    response_text = hunger.process_request(session['user_phone'], lang, food_type, session.get('city', 'Unknown'))
    
    # Notify Donors - Use socketio.emit for global broadcast
    print(f"[BROADCAST] Notifying donors about {food_type} request")
    socketio.emit('new_food_request', {
        'phone': session['user_phone'],
        'city': session.get('city', 'Unknown'),
        'type': food_type,
        'timestamp': time.strftime("%H:%M:%S"),
        'lat': session.get('lat'),
        'lng': session.get('lng')
    })
    
    path = generate_ai_voice(response_text, lang)
    try:
        print(f"\n[AI RESPONSE] {response_text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {response_text}'}, broadcast=True)
    audio.stop_buffer()
    audio.play_voice(path)

@socketio.on('donor_accept')
def handle_donor_accept(data):
    requester_phone = data['phone']
    donor_name = data.get('donor_name', 'A kind donor')
    print(f"\n[DONOR] Request Accepted by {donor_name} for {requester_phone}")
    
    emit('status_update', {'msg': f'Donor {donor_name} accepted request!'}, broadcast=True)
    
    lang = session.get('language', 'en')
    in_zone = session.get('in_zone', False)
    group_type = session.get('group_type', 'group')
    
    import random
    from core import db_manager
    
    if in_zone and 'Vrrudhashrama' in donor_name:
        # Update the handshake monitor database dynamically!
        try:
            db_manager.verify_vrrudhashrama_transactions()
        except Exception as e:
            print(f"[DATABASE ERROR] {e}")
            
        if lang == 'en':
            responses = [
                "Vrrudhashrama has accepted your request. Please walk to the centre to receive your meal.",
                "Your request is accepted by Vrrudhashrama. The centre is nearby, please proceed there to get your food.",
                "Good news, Vrrudhashrama accepted your request. Since you are in the area, kindly walk over to the ashram."
            ]
        else:
            responses = [
                "ವೃದ್ಧಾಶ್ರಮವು ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಸ್ವೀಕರಿಸಿದೆ. ದಯವಿಟ್ಟು ಊಟವನ್ನು ಸ್ವೀಕರಿಸಲು ಕೇಂದ್ರಕ್ಕೆ ನಡೆದು ಹೋಗಿ.",
                "ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ವೃದ್ಧಾಶ್ರಮ ಸ್ವೀಕರಿಸಿದೆ. ಕೇಂದ್ರವು ಹತ್ತಿರದಲ್ಲಿದೆ, ದಯವಿಟ್ಟು ಅಲ್ಲಿಗೆ ತೆರಳಿ.",
                "ಒಳ್ಳೆಯ ಸುದ್ದಿ, ವೃದ್ಧಾಶ್ರಮ ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಒಪ್ಪಿಕೊಂಡಿದೆ. ದಯವಿಟ್ಟು ಆಶ್ರಮಕ್ಕೆ ನಡೆದು ಬನ್ನಿ."
            ]
        text = random.choice(responses)
        print(f"\n[RANDOM ACCEPTANCE]\n{text}\n")
    else:
        if lang == 'en':
            responses = [
                f"The donor {donor_name} has accepted your food request. They will contact you shortly.",
                f"Great news! {donor_name} accepted your request and will organize the delivery."
            ]
        else:
            responses = [
                f"ದಾನಿ {donor_name} ನಿಮ್ಮ ಆಹಾರದ ವಿನಂತಿಯನ್ನು ಸ್ವೀಕರಿಸಿದ್ದಾರೆ. ಅವರು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ.",
                f"ಒಳ್ಳೆಯ ಸುದ್ದಿ! {donor_name} ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಸ್ವೀಕರಿಸಿದ್ದಾರೆ."
            ]
        text = random.choice(responses)
        print(f"\n[RANDOM ACCEPTANCE]\n{text}\n")
        
    if lang == 'en':
        text += " Please provide feedback: Press 1 if this information was helpful, or press 2 if it was not."
    else:
        text += " ದಯವಿಟ್ಟು ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಿ: ಈ ಮಾಹಿತಿಯು ಸಹಾಯಕವಾಗಿದ್ದರೆ 1 ಒತ್ತಿರಿ, ಅಥವಾ ಇಲ್ಲದಿದ್ದರೆ 2 ಒತ್ತಿರಿ."
        
    path = generate_ai_voice(text, lang)
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI (To User): {text}'}, broadcast=True)
    audio.play_voice(path)
    # Also notify the dashboard to show the Dial button
    emit('donor_accepted_notify', {'donor_name': donor_name}, broadcast=True)

@socketio.on('donor_dial')
def handle_donor_dial():
    print(f"\n[ACTION] User Dialing Donor")
    emit('status_update', {'msg': 'Dialing donor... connecting call.'}, broadcast=True)
    lang = session.get('language', 'en')
    text = "Connecting your call to the donor. Please stay on the line. Thank you for using Zero Hunger." if lang == 'en' else "ದಾನಿಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಕರೆಯನ್ನು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ. ದಯವಿಟ್ಟು ಲೈನ್‌ನಲ್ಲಿರಿ. ಜೀರೋ ಹಂಗರ್ ಬಳಸಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು."
    path = generate_ai_voice(text, lang)
    try:
        print(f"\n[AI RESPONSE] {text}")
    except UnicodeEncodeError:
        print(f"\n[AI RESPONSE] (Kannada Text - Display Error in Console)")
    audio.play_voice(path)

@socketio.on('feedback_action')
def handle_feedback_action(data):
    choice = data.get('choice')
    lang = session.get('language', 'en')
    
    if choice == 1:
        text = "Thank you for your positive feedback! We are glad we could help." if lang == 'en' else "ನಿಮ್ಮ ಸಕಾರಾತ್ಮಕ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು! ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ನಾವು ಸಂತೋಷಪಡುತ್ತೇವೆ."
    else:
        text = "Thank you for your feedback. We will work on improving our service." if lang == 'en' else "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು. ನಮ್ಮ ಸೇವೆಯನ್ನು ಸುಧಾರಿಸಲು ನಾವು ಕೆಲಸ ಮಾಡುತ್ತೇವೆ."
    
    try:
        print(f"\n{text}")
    except UnicodeEncodeError:
        print("\nThank you for the feedback")
        
    path = generate_ai_voice(text, lang)
    emit('status_update', {'msg': text}, broadcast=True)
    audio.play_voice(path)

# --- HELPER FUNCTIONS ---

def generate_ai_voice(text, lang):
    """
    Utility to bridge Brain text output to Audio playback.
    Uses unique filenames to avoid Windows file-locking issues.
    """
    # Create unique filename using timestamp
    filename = f"reply_{int(time.time() * 1000)}.mp3"
    file_path = os.path.abspath(os.path.join("static", "audio", filename))
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    
    try:
        tts = gTTS(text, lang=lang)
        tts.save(file_path)
        print("[TTS SUCCESS] TTS successful")
    except Exception as e:
        print(f"Error generating TTS: {e}")
        
    return file_path

if __name__ == '__main__':
    print("Vistara AI Server Active...")
    db_manager.init_db()
    socketio.run(app, debug=True, host='0.0.0.0', port=5000, allow_unsafe_werkzeug=True)